[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# [target.arm64-apple-darwin]
# rustflags = ["-C", "link-args=-weak_framework Metal"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.1", features = ["api-all"] }
pathdiff = "0.2.1"
csv = "1.1.6"
opencv-yolov5 = { git = "https://github.com/bencevans/rust-opencv-yolov5" }
eta = "0.2.2"
image = { version = "0.24.5", features = ["rgb"] }
imageproc = "0.23.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]

builtin = []


# [env]
# RUSTFLAGS='-L vendor/opencv/build/3rdparty/lib  -l ittnotify -l libjpeg-turbo  -l libpng -l libprotobuf -l tegra_hal -l zlib -l framework=OpenCL -l framework=Accelerate' OPENCV_DISABLE_PROBES=1 OPENCV_LINK_PATHS='vendor/install/lib/opencv4/3rdparty/lib,vendor/opencv/build/install/lib' OPENCV_LINK_LIBS='opencv_core,opencv_imgproc,opencv_imgcodecs,opencv_dnn' OPENCV_INCLUDE_PATHS='vendor/opencv/build/install/include/opencv4'
