name: 'Build MacOS'
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: wget -q https://static.bencevans.io/md_v5a.0.0.onnx
      - name: install app dependencies and build it
        run: npm install && npm run tauri build
      - uses: tauri-apps/tauri-action@v0
